import { Image, Platform } from "react-native";
import type { PublicCatalogProvider, PublicCatalogSnapshot } from "@/types/catalog";

// On native, `require("*.jpg")` returns an opaque numeric asset id that only
// Image.resolveAssetSource() can turn into a URI. On web, Metro's asset
// plugin already resolves the require to a { uri, width, height } object —
// react-native-web's Image has no resolveAssetSource to call on it at all.
function assetUri(mod: number | { uri: string }): string {
  return Platform.OS === "web"
    ? (mod as { uri: string }).uri
    : Image.resolveAssetSource(mod as number).uri;
}

const braidsUri = assetUri(require("../../assets/images/braids_cover.jpg"));
const bridalGlamUri = assetUri(require("../../assets/images/bridal_glam_cover.jpg"));
const mensGroomingUri = assetUri(require("../../assets/images/mens_grooming_cover.jpg"));
const spaMassageUri = assetUri(require("../../assets/images/spa_massage_cover.jpg"));

const MOCK_PROVIDERS: PublicCatalogProvider[] = [
  // 4 Full/claimed, bookingEnabled: true
  {
    id: "mock-1",
    slug: "braid-bar-nairobi",
    name: "The Braid Bar Nairobi",
    industry: "beauty",
    categoryId: "hair",
    subcategory: "Braiding",
    mainOffering: "Braids",
    area: "Kilimani",
    distance: "1.2 km",
    address: "123 Ngong Rd, Kilimani, Nairobi",
    location: {
      latitude: -1.2921,
      longitude: 36.782,
      fullAddress: "123 Ngong Rd, Kilimani, Nairobi",
      area: "Kilimani",
      city: "Nairobi",
      locationType: "FIXED_VENUE",
      serviceAreas: [],
      landmark: "Near Prestige Plaza",
      parkingAvailable: true,
    },
    paymentSettings: {
      allowPayAtVenue: true,
      requiresDeposit: false,
      instantConfirmation: true,
      acceptedPaymentMethods: ["M-Pesa"],
    },
    hours: "09:00-19:00",
    phone: "+254700000000",
    cover: braidsUri,
    gallery: [braidsUri],
    verified: true,
    openNow: true,
    bookingEnabled: true,
    limitedListing: false,
    bookingMethod: "kilipicks",
    recommended: true,
    featured: true,
    wouldReturn: 95,
    trustMetric: "Highly Rated",
    partnershipStatus: "signed",
    publicationStatus: "published",
    serviceIds: ["srv-1", "srv-2"],
    specialistIds: ["sp-1"],
    highlights: ["Free WiFi"],
    facilities: ["Parking"],
    publicContacts: { phone: "+254700000000" },
    startingPrice: 3500,
    rating: 4.8,
    about: "The Braid Bar Nairobi is your premier destination for knotless braids and cornrows.",
    team: [{ id: "t-1", name: "Sarah", role: "Lead Braider" }],
    reviews: [{ id: "r-1", author: "Jane D.", rating: 5, text: "Best braids in town!", date: "2023-10-01" }],
    portfolio: [braidsUri],
    otherSection: "Additional information about our salon.",
  },
  {
    id: "mock-2",
    slug: "bridal-glam-studio",
    name: "Bridal Glam Studio",
    industry: "beauty",
    categoryId: "makeup",
    subcategory: "Bridal",
    mainOffering: "Bridal glam",
    area: "Westlands",
    distance: "2.5 km",
    address: "Westlands Rd, Nairobi",
    location: {
      latitude: -1.268,
      longitude: 36.805,
      fullAddress: "Westlands Rd, Nairobi",
      area: "Westlands",
      city: "Nairobi",
      locationType: "FIXED_VENUE",
      serviceAreas: [],
      landmark: "Behind Sarit Centre",
      parkingAvailable: true,
    },
    paymentSettings: {
      allowPayAtVenue: true,
      requiresDeposit: true,
      instantConfirmation: false,
      acceptedPaymentMethods: ["M-Pesa"],
    },
    hours: "08:00-18:00",
    phone: "+254700000000",
    cover: bridalGlamUri,
    gallery: [bridalGlamUri],
    verified: true,
    openNow: true,
    bookingEnabled: true,
    limitedListing: false,
    bookingMethod: "kilipicks",
    recommended: false,
    featured: false,
    wouldReturn: 100,
    trustMetric: "Top Pro",
    partnershipStatus: "signed",
    publicationStatus: "published",
    serviceIds: ["srv-3"],
    specialistIds: ["sp-2"],
    highlights: [],
    facilities: [],
    publicContacts: { phone: "+254700000000" },
    startingPrice: 5000,
    rating: 4.9,
  },
  {
    id: "mock-3",
    slug: "gentlemans-cut",
    name: "The Gentleman's Cut",
    industry: "beauty",
    categoryId: "barber",
    subcategory: "Men's grooming",
    mainOffering: "Men's grooming",
    area: "Kilimani",
    distance: "0.8 km",
    address: "Argwings Kodhek Rd",
    location: {
      latitude: -1.295,
      longitude: 36.78,
      fullAddress: "Argwings Kodhek Rd, Kilimani, Nairobi",
      area: "Kilimani",
      city: "Nairobi",
      locationType: "FIXED_VENUE",
      serviceAreas: [],
      landmark: "Yaya Centre",
      parkingAvailable: true,
    },
    paymentSettings: {
      allowPayAtVenue: true,
      requiresDeposit: false,
      instantConfirmation: true,
      acceptedPaymentMethods: ["M-Pesa"],
    },
    hours: "09:00-20:00",
    phone: "+254700000000",
    cover: mensGroomingUri,
    gallery: [mensGroomingUri],
    verified: true,
    openNow: true,
    bookingEnabled: true,
    limitedListing: false,
    bookingMethod: "kilipicks",
    recommended: true,
    featured: false,
    wouldReturn: 92,
    trustMetric: "Popular",
    partnershipStatus: "signed",
    publicationStatus: "published",
    serviceIds: ["srv-4", "srv-5"],
    specialistIds: ["sp-3"],
    highlights: ["Free Drink"],
    facilities: ["TV"],
    publicContacts: { phone: "+254700000000" },
    startingPrice: 1500,
    rating: 4.7,
  },
  {
    id: "mock-4",
    slug: "zen-spa-massage",
    name: "Zen Spa & Massage",
    industry: "wellness",
    categoryId: "spa",
    subcategory: "Massage",
    mainOffering: "Spa & Massage",
    area: "Lavington",
    distance: "3.1 km",
    address: "James Gichuru Rd",
    location: {
      latitude: -1.285,
      longitude: 36.76,
      fullAddress: "James Gichuru Rd, Lavington, Nairobi",
      area: "Lavington",
      city: "Nairobi",
      locationType: "FIXED_VENUE",
      serviceAreas: [],
      landmark: "Lavington Mall",
      parkingAvailable: true,
    },
    paymentSettings: {
      allowPayAtVenue: false,
      requiresDeposit: true,
      instantConfirmation: true,
      acceptedPaymentMethods: ["M-Pesa"],
    },
    hours: "10:00-21:00",
    phone: "+254700000000",
    cover: spaMassageUri,
    gallery: [spaMassageUri],
    verified: true,
    openNow: true,
    bookingEnabled: true,
    limitedListing: false,
    bookingMethod: "kilipicks",
    recommended: false,
    featured: true,
    wouldReturn: 88,
    trustMetric: "Verified",
    partnershipStatus: "signed",
    publicationStatus: "published",
    serviceIds: ["srv-6"],
    specialistIds: ["sp-4"],
    highlights: ["Quiet Environment"],
    facilities: ["Showers"],
    publicContacts: { phone: "+254700000000" },
    startingPrice: 6000,
    rating: 4.6,
  },

  // 2 Full/claimed, bookingEnabled: false (honest-disabled state)
  {
    id: "mock-5",
    slug: "nails-by-jane",
    name: "Nails by Jane",
    industry: "beauty",
    categoryId: "nails",
    subcategory: "Manicure",
    mainOffering: "Acrylics",
    area: "Westlands",
    distance: "2.1 km",
    address: "Mpaka Rd",
    location: {
      latitude: -1.265,
      longitude: 36.802,
      fullAddress: "Mpaka Rd, Westlands",
      area: "Westlands",
      city: "Nairobi",
      locationType: "FIXED_VENUE",
      serviceAreas: [],
      landmark: "",
      parkingAvailable: false,
    },
    paymentSettings: {
      allowPayAtVenue: true,
      requiresDeposit: false,
      instantConfirmation: false,
      acceptedPaymentMethods: ["M-Pesa"],
    },
    hours: "Closed today",
    phone: "+254700000000",
    cover: "provider-placeholder://mock-5",
    gallery: [],
    verified: true,
    openNow: false,
    bookingEnabled: false,
    limitedListing: false,
    bookingMethod: "disabled",
    recommended: false,
    featured: false,
    wouldReturn: 0,
    trustMetric: "New",
    partnershipStatus: "signed",
    publicationStatus: "published",
    serviceIds: [],
    specialistIds: [],
    highlights: [],
    facilities: [],
    publicContacts: { phone: "+254700000000" },
    startingPrice: 1200,
    rating: 0,
  },
  {
    id: "mock-6",
    slug: "glow-up-makeup",
    name: "Glow Up Makeup",
    industry: "beauty",
    categoryId: "makeup",
    subcategory: "Evening Makeup",
    mainOffering: "Evening Makeup",
    area: "Kilimani",
    distance: "1.5 km",
    address: "Lenana Rd",
    location: {
      latitude: -1.29,
      longitude: 36.79,
      fullAddress: "Lenana Rd, Kilimani",
      area: "Kilimani",
      city: "Nairobi",
      locationType: "FIXED_VENUE",
      serviceAreas: [],
      landmark: "",
      parkingAvailable: true,
    },
    paymentSettings: {
      allowPayAtVenue: true,
      requiresDeposit: false,
      instantConfirmation: false,
      acceptedPaymentMethods: ["M-Pesa"],
    },
    hours: "09:00-18:00",
    phone: "+254700000000",
    cover: "provider-placeholder://mock-6",
    gallery: [],
    verified: true,
    openNow: true,
    bookingEnabled: false,
    limitedListing: false,
    bookingMethod: "disabled",
    recommended: false,
    featured: false,
    wouldReturn: 0,
    trustMetric: "Verified",
    partnershipStatus: "signed",
    publicationStatus: "published",
    serviceIds: [],
    specialistIds: [],
    highlights: [],
    facilities: [],
    publicContacts: { phone: "+254700000000" },
    startingPrice: undefined,
    rating: 0,
  },

  // 6 limitedListing: true
  ...Array.from({ length: 6 }).map((_, i): PublicCatalogProvider => ({
    id: `mock-dir-${i + 1}`,
    slug: `mock-dir-${i + 1}`,
    name: `Directory Salon ${i + 1}`,
    industry: "beauty",
    categoryId: "hair",
    subcategory: null,
    mainOffering: "Hair",
    area: "Kilimani", // Keeping area same to group them in "Near Kilimani"
    distance: `${0.5 + i * 0.2} km`,
    address: "Kilimani, Nairobi",
    location: {
      latitude: -1.29,
      longitude: 36.78,
      fullAddress: "Kilimani, Nairobi",
      area: "Kilimani",
      city: "Nairobi",
      locationType: "FIXED_VENUE",
      serviceAreas: [],
      landmark: "",
      parkingAvailable: false,
    },
    paymentSettings: {
      allowPayAtVenue: true,
      requiresDeposit: false,
      instantConfirmation: false,
      acceptedPaymentMethods: [],
    },
    hours: "",
    phone: "+254700000000",
    cover: "provider-placeholder://mock-dir",
    gallery: [],
    verified: false,
    openNow: false,
    bookingEnabled: false,
    limitedListing: true,
    bookingMethod: "disabled",
    recommended: false,
    featured: false,
    wouldReturn: 0,
    trustMetric: "New",
    partnershipStatus: "unsigned",
    publicationStatus: "published",
    serviceIds: [],
    specialistIds: [],
    highlights: [],
    facilities: [],
    publicContacts: {},
    startingPrice: undefined,
    rating: 0,
  }))
];

export const MOCK_CATALOG: PublicCatalogSnapshot = {
  providers: MOCK_PROVIDERS,
  services: [
    {
      id: "srv-1",
      providerId: "mock-1",
      categoryId: "hair",
      industry: "beauty",
      name: "Knotless Braids",
      description: "Medium knotless braids with extensions included.",
      durationMinutes: 180,
      price: 3500,
      priceType: "fixed",
      bookingEnabled: true,
      active: true,
    },
    {
      id: "srv-2",
      providerId: "mock-1",
      categoryId: "hair",
      industry: "beauty",
      name: "Cornrows",
      description: "Simple straight back cornrows.",
      durationMinutes: 60,
      price: 1500,
      priceType: "fixed",
      bookingEnabled: true,
      active: true,
    },
    {
      id: "srv-3",
      providerId: "mock-2",
      categoryId: "makeup",
      industry: "beauty",
      name: "Bridal Makeup",
      description: "Full face glam with lashes for the bride.",
      durationMinutes: 120,
      price: 5000,
      priceType: "fixed",
      bookingEnabled: true,
      active: true,
    },
    {
      id: "srv-4",
      providerId: "mock-3",
      categoryId: "barber",
      industry: "beauty",
      name: "Fade Haircut",
      description: "Clean fade with hot towel finish.",
      durationMinutes: 45,
      price: 1500,
      priceType: "fixed",
      bookingEnabled: true,
      active: true,
    },
    {
      id: "srv-5",
      providerId: "mock-3",
      categoryId: "barber",
      industry: "beauty",
      name: "Beard Trim",
      description: "Beard shaping and trim.",
      durationMinutes: 30,
      price: 800,
      priceType: "fixed",
      bookingEnabled: true,
      active: true,
    },
    {
      id: "srv-6",
      providerId: "mock-4",
      categoryId: "spa",
      industry: "wellness",
      name: "Deep Tissue Massage",
      description: "60 minute deep tissue full body massage.",
      durationMinutes: 60,
      price: 6000,
      priceType: "fixed",
      bookingEnabled: true,
      active: true,
    }
  ],
  availability: [], // Not fully implemented in dummy data for now
  managedMerchantIds: [],
  managedServiceIds: [],
  generatedAt: new Date().toISOString(),
};
