ALTER TABLE businesses
ADD COLUMN about TEXT,
ADD COLUMN team JSONB NOT NULL DEFAULT '[]',
ADD COLUMN reviews JSONB NOT NULL DEFAULT '[]',
ADD COLUMN portfolio JSONB NOT NULL DEFAULT '[]',
ADD COLUMN other_section TEXT;
