ALTER TABLE businesses
ADD COLUMN onboarding_step INTEGER NOT NULL DEFAULT 1,
ADD COLUMN submitted_at TIMESTAMP(3) NULL,
ADD COLUMN travel_radius INTEGER NULL DEFAULT 15,
ADD COLUMN active_preset VARCHAR(100) NULL DEFAULT 'Mon – Fri, 9 – 6';
